name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel via rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /home/keadilan/sys.keadilankb.com/
          remote_host: sys.keadilankb.com
          remote_user: keadilan
          remote_key: ${{ secrets.ddQA60IioCRqmDiPusKZA7kNcIAQvi6l+mhpF8uccMI  }}
