---
deployment:
  tasks:
    - export DEPLOYPATH=/home/keadilan/sys.keadilankb.com

    # Sync all files except ignored ones
    - /bin/rsync -av --exclude=".git" --exclude=".github" --exclude="node_modules" --exclude="tests" ./ $DEPLOYPATH

    # Set permissions
    - /bin/chmod -R 775 $DEPLOYPATH/storage
    - /bin/chmod -R 775 $DEPLOYPATH/bootstrap/cache

    # Clear & optimize Laravel caches
    - /usr/local/bin/php $DEPLOYPATH/artisan config:clear
    - /usr/local/bin/php $DEPLOYPATH/artisan cache:clear
    - /usr/local/bin/php $DEPLOYPATH/artisan route:clear
    - /usr/local/bin/php $DEPLOYPATH/artisan view:clear
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
