name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
        - name: Upload to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-directory: ${{ secrets.FTP_DIR }}
