name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.CPANEL_FTP_HOST }}
          username: ${{ secrets.CPANEL_FTP_USER }}
          password: ${{ secrets.CPANEL_FTP_PASS }}
          protocol: ftps
          local-dir: ./
          server-dir: /home/keadilan/sys.keadilankb.com/

      # (Optional) Run Laravel optimization commands remotely
      - name: SSH to cPanel and run artisan commands
        if: always()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CPANEL_SSH_HOST }}
          username: ${{ secrets.CPANEL_SSH_USER }}
          password: ${{ secrets.CPANEL_SSH_PASS }}
          port: 22
          script: |
            cd /home/keadilan/sys.keadilankb.com
            php artisan config:clear
            php artisan config:cache
            php artisan route:clear
            php artisan route:cache
            php artisan view:clear
            php artisan storage:link --force
            php artisan migrate --force
            chmod -R 755 storage bootstrap/cache
